name: Lint

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - main
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  lua-check:
    name: Lua Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    if: (github.actor != 'dependabot[bot]')

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    # Optional step to run on only changed files
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@54849deb963ca9f24185fb5de2965e002d066e6b # v37
      with:
        files: |
          **.lua

    - name: Lua Check
      if: steps.changed-files.outputs.any_changed == 'true'
      uses: Kong/public-shared-actions/code-check-actions/lua-lint@v1
      with:
        additional_args: '--no-default-config --config .luacheckrc'
        files: ${{ steps.changed-files.outputs.all_changed_files }}
